Features
badger-99/Hello-world pull request #2
Opened 2023-04-25 22:14 UTC by badger-99

2023-04-25 22:47 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @badger-99, 
I'm Andres.

While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Linters are correctly set up and passing! 🥇 
✅ Descriptive commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

You did a great job working on this milestone, however, there's still some room to improve! 🤓 

### Professional Pull Request

![Screenshot from 2023-04-25 17-33-22](https://user-images.githubusercontent.com/77069011/234420411-de328051-c4ff-4d21-8fc2-5139d5d5cbf3.png)

- [ ] Please consider updating your PR title to be more descriptive about the feature you're introducing, and not the generic title `Features`. For example, a good title could be "Hello Microverse". 🔧 

- [ ] Also, please consider adding a detailed description of the changes you're introducing in the PR, you could follow this template: 🔧 

```markdown
## In this Milestone, I introduced the following changes:

- Change 1
- Change 2
- ...
```

- [x] Also, for future projects, It would be good to use a better branch name describing the feature you're developing, in this case, `hello-microverse-html` or similar would've been more descriptive. ⚠️  **PLEASE DO NOT TRY TO CHANGE THIS ONE AS IT CAN CAUSE SOME PROBLEMS WITH THE GIT HISTORY, TAKE THIS ADVICE FOR FUTURE MILESTONES!** 🤓 🔧 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 22:47 UTC, anagudelogu commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] You did great using the correct README template to document your project! 🚀 However, it is crucial to keep all the non-optional sections and fill them with their respective information about the project, I know it could feel a little overwhelming, especially for this first project, but take this as a practice to sharpen your documentation skills since they are essential in our industry! 🤓 🔧 

Please include all the missing sections from the [README template.](https://github.com/microverseinc/readme-template) 🤖

2023-04-25 22:47 UTC, anagudelogu commented on test.md
> +# This file should be ignored by git.
- [ ] As this file content states, this file should be ignored by git and not be present here as a change. Please make sure that Git is actually ignoring this file! 🤓 🔧

2023-04-26 23:27 UTC, Efiamotu-1 approved these changes
Hi @badger-99 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow or Gitflow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 23:33 UTC, merged